### ISSUE TITLE
Rotation signature should be `Float -> Float -> Float -> Attribute msg`

### ISSUE THREAD

**Issue by gabrielperales** [halfzebra/elm-aframe#15]
I don't know why you are allowing just integer degrees as parameters [here](https://github.com/halfzebra/elm-aframe/blob/master/src/AFrame/Primitives/Attributes.elm#L124).

**Comment by halfzebra** [comment]
@gabrielperales thanks for contributing!

I couldn't find any mentions of `rotation` values being floats in the docs/examples or even in Three.js since it relies on [Vector3](https://threejs.org/docs/#api/math/Vector3) if I understand it correctly.

It [looks like](https://github.com/mrdoob/three.js/blob/dev/src/math/Vector3.js) it's possible to use float values, so this issue makes perfect sense! 👍
